In [1]:
import numpy as np

In [5]:
data = np.array([
    [2,5,8],
    [5,10,10],
    [8,9,7],
    [3,4,5]
],dtype=np.float64)

In [21]:
from sklearn.preprocessing import StandardScaler
"""
 scaled_data = (x-mean)/std
"""
scaler = StandardScaler()
scaler.fit(data)
scaled_data = scaler.transform(data)
print(scaled_data)
print(scaler.mean_)

[[-1.09108945 -0.78446454  0.2773501 ]
 [ 0.21821789  1.17669681  1.38675049]
 [ 1.52752523  0.78446454 -0.2773501 ]
 [-0.65465367 -1.17669681 -1.38675049]]
[ 4.5  7.   7.5]


In [22]:
from sklearn.preprocessing import MinMaxScaler
"""
for (-1,1)
2,5,8,3

std_dev = 2-2/8-2 , 5-2/8-2, 8-2/8-2, 3-2/8-2
        = 0, 0.5, 1, 0.166
X_scaled = 0*(1-(-1)) + (-1) , 0.5*(1-(-1)) + (-1), 1*(1-(-1)) + (-1), 0.166*(1-(-1) + (-1))
         = 0-1, 1-1, 2-1, 0.332-1 
         = -1,0,1,0.667
"""
minmaxscaler = MinMaxScaler((-1,1))
minmaxscaler.fit(data)
scaled_data = minmaxscaler.transform(data)
print(scaled_data)

[[-1.         -0.66666667  0.2       ]
 [ 0.          1.          1.        ]
 [ 1.          0.66666667 -0.2       ]
 [-0.66666667 -1.         -1.        ]]


In [12]:
from sklearn.preprocessing import Normalizer
"""
"""
normalizer = Normalizer()
normalizer.fit(data)
norm_data = normalizer.transform(data)
print(norm_data)

[[ 0.20739034  0.51847585  0.82956136]
 [ 0.33333333  0.66666667  0.66666667]
 [ 0.57436653  0.64616234  0.50257071]
 [ 0.42426407  0.56568542  0.70710678]]


In [49]:
import pandas as pd
df = pd.DataFrame({
    'first':['one','two','one','three'],
    'second':[1,6,4,1],
    'third':[5.7,2.6,2.4,3.3],
    'fourth':['a','b','b','a'],
    'fifth':[6,1,2,3]
})
print(df.dtypes)
df.head()

first      object
second      int64
third     float64
fourth     object
fifth       int64
dtype: object


first  second  third fourth  fifth
0    one       1    5.7      a      6
1    two       6    2.6      b      1
2    one       4    2.4      b      2
3  three       1    3.3      a      3

In [62]:
df_n = df.copy()
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
for col in df_n.columns:
    if df_n[col].dtype != np.float64 and df_n[col].dtype != np.int64:
            le.fit(df_n[col])
            df_n[col] = le.transform(df_n[col])
            
print(df_n.dtypes)
df_n.head()

first       int64
second      int64
third     float64
fourth      int64
fifth       int64
dtype: object


first  second  third  fourth  fifth
0      0       1    5.7       0      6
1      2       6    2.6       1      1
2      0       4    2.4       1      2
3      1       1    3.3       0      3

In [64]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(categorical_features=[0,3])
ohe.fit(df_n)
ohe.transform(df_n).toarray()

array([[ 1. ,  0. ,  0. ,  1. ,  0. ,  1. ,  5.7,  6. ],
       [ 0. ,  0. ,  1. ,  0. ,  1. ,  6. ,  2.6,  1. ],
       [ 1. ,  0. ,  0. ,  0. ,  1. ,  4. ,  2.4,  2. ],
       [ 0. ,  1. ,  0. ,  1. ,  0. ,  1. ,  3.3,  3. ]])

In [65]:
import pandas as pd
df = pd.DataFrame({
    'first':['one','two','one','three'],
    'second':[1,6,4,1],
    'third':[5.7,2.6,2.4,3.3],
    'fourth':['a','b','b','a'],
    'fifth':[6,1,2,3]
})
print(df.dtypes)
df.head()

first      object
second      int64
third     float64
fourth     object
fifth       int64
dtype: object


first  second  third fourth  fifth
0    one       1    5.7      a      6
1    two       6    2.6      b      1
2    one       4    2.4      b      2
3  three       1    3.3      a      3

In [67]:
pd.get_dummies(
    df,columns=['first','fourth'],prefix=['ohefirst','ohefourth']
)

second  third  fifth  ohefirst_one  ohefirst_three  ohefirst_two  \
0       1    5.7      6             1               0             0   
1       6    2.6      1             0               0             1   
2       4    2.4      2             1               0             0   
3       1    3.3      3             0               1             0   

   ohefourth_a  ohefourth_b  
0            1            0  
1            0            1  
2            0            1  
3            1            0